/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedDestinationsIndexRouteImport } from './routes/_authenticated/destinations/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedCajaIndexRouteImport } from './routes/_authenticated/caja/index'
import { Route as AuthenticatedAgenciasIndexRouteImport } from './routes/_authenticated/agencias/index'
import { Route as ApiAuthVerifyEmailRouteImport } from './routes/api/auth/verify-email'
import { Route as AuthenticatedUsersNuevoRouteImport } from './routes/_authenticated/users/nuevo'
import { Route as AuthenticatedSettingsServiceChargesRouteImport } from './routes/_authenticated/settings_.service-charges'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSalesSeatsRouteImport } from './routes/_authenticated/sales/seats'
import { Route as AuthenticatedSalesPaymentRouteImport } from './routes/_authenticated/sales/payment'
import { Route as AuthenticatedSalesCheckoutRouteImport } from './routes/_authenticated/sales/checkout'
import { Route as AuthenticatedReportsVentasSinBoletoRouteImport } from './routes/_authenticated/reports/ventas-sin-boleto'
import { Route as AuthenticatedReportsSerieTemporalRouteImport } from './routes/_authenticated/reports/serie-temporal'
import { Route as AuthenticatedReportsResumenFinancieroRouteImport } from './routes/_authenticated/reports/resumen-financiero'
import { Route as AuthenticatedReportsPorVendedorRouteImport } from './routes/_authenticated/reports/por-vendedor'
import { Route as AuthenticatedReportsPorServicioRouteImport } from './routes/_authenticated/reports/por-servicio'
import { Route as AuthenticatedReportsPorRutaRouteImport } from './routes/_authenticated/reports/por-ruta'
import { Route as AuthenticatedReportsPorMetodoPagoRouteImport } from './routes/_authenticated/reports/por-metodo-pago'
import { Route as AuthenticatedReportsPorAgenciaRouteImport } from './routes/_authenticated/reports/por-agencia'
import { Route as AuthenticatedReportsMovimientosRouteImport } from './routes/_authenticated/reports/movimientos'
import { Route as AuthenticatedReportsEstadoVentasRouteImport } from './routes/_authenticated/reports/estado-ventas'
import { Route as AuthenticatedReportsConciliacionBancardRouteImport } from './routes/_authenticated/reports/conciliacion-bancard'
import { Route as AuthenticatedReportsComparativoRouteImport } from './routes/_authenticated/reports/comparativo'
import { Route as AuthenticatedReportsAnomaliasRouteImport } from './routes/_authenticated/reports/anomalias'
import { Route as AuthenticatedDestinationsNuevoRouteImport } from './routes/_authenticated/destinations/nuevo'
import { Route as AuthenticatedClientsNuevoRouteImport } from './routes/_authenticated/clients/nuevo'
import { Route as AuthenticatedAgenciasNuevaRouteImport } from './routes/_authenticated/agencias/nueva'
import { Route as AuthenticatedSettingsExternalDataIndexRouteImport } from './routes/_authenticated/settings/external-data/index'
import { Route as AuthenticatedDestinationsIdIndexRouteImport } from './routes/_authenticated/destinations/$id/index'
import { Route as AuthenticatedClientsEmailIndexRouteImport } from './routes/_authenticated/clients/$email/index'
import { Route as AuthenticatedAgenciasIdIndexRouteImport } from './routes/_authenticated/agencias/$id/index'
import { Route as AuthenticatedUsersIdEditarRouteImport } from './routes/_authenticated/users/$id/editar'
import { Route as AuthenticatedSettingsServiceChargesNuevoRouteImport } from './routes/_authenticated/settings_.service-charges_.nuevo'
import { Route as AuthenticatedSettingsExternalDataDayConfigurationRouteImport } from './routes/_authenticated/settings/external-data/day-configuration'
import { Route as AuthenticatedDestinationsIdEditarRouteImport } from './routes/_authenticated/destinations/$id/editar'
import { Route as AuthenticatedAgenciasIdEditarRouteImport } from './routes/_authenticated/agencias/$id/editar'
import { Route as AuthenticatedSettingsServiceChargesIdEditarRouteImport } from './routes/_authenticated/settings_.service-charges_.$id.editar'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDestinationsIndexRoute =
  AuthenticatedDestinationsIndexRouteImport.update({
    id: '/destinations/',
    path: '/destinations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCajaIndexRoute = AuthenticatedCajaIndexRouteImport.update({
  id: '/caja/',
  path: '/caja/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgenciasIndexRoute =
  AuthenticatedAgenciasIndexRouteImport.update({
    id: '/agencias/',
    path: '/agencias/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAuthVerifyEmailRoute = ApiAuthVerifyEmailRouteImport.update({
  id: '/api/auth/verify-email',
  path: '/api/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersNuevoRoute = AuthenticatedUsersNuevoRouteImport.update({
  id: '/users/nuevo',
  path: '/users/nuevo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsServiceChargesRoute =
  AuthenticatedSettingsServiceChargesRouteImport.update({
    id: '/settings_/service-charges',
    path: '/settings/service-charges',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSalesSeatsRoute = AuthenticatedSalesSeatsRouteImport.update({
  id: '/sales/seats',
  path: '/sales/seats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesPaymentRoute =
  AuthenticatedSalesPaymentRouteImport.update({
    id: '/sales/payment',
    path: '/sales/payment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesCheckoutRoute =
  AuthenticatedSalesCheckoutRouteImport.update({
    id: '/sales/checkout',
    path: '/sales/checkout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsVentasSinBoletoRoute =
  AuthenticatedReportsVentasSinBoletoRouteImport.update({
    id: '/reports/ventas-sin-boleto',
    path: '/reports/ventas-sin-boleto',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsSerieTemporalRoute =
  AuthenticatedReportsSerieTemporalRouteImport.update({
    id: '/reports/serie-temporal',
    path: '/reports/serie-temporal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsResumenFinancieroRoute =
  AuthenticatedReportsResumenFinancieroRouteImport.update({
    id: '/reports/resumen-financiero',
    path: '/reports/resumen-financiero',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsPorVendedorRoute =
  AuthenticatedReportsPorVendedorRouteImport.update({
    id: '/reports/por-vendedor',
    path: '/reports/por-vendedor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsPorServicioRoute =
  AuthenticatedReportsPorServicioRouteImport.update({
    id: '/reports/por-servicio',
    path: '/reports/por-servicio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsPorRutaRoute =
  AuthenticatedReportsPorRutaRouteImport.update({
    id: '/reports/por-ruta',
    path: '/reports/por-ruta',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsPorMetodoPagoRoute =
  AuthenticatedReportsPorMetodoPagoRouteImport.update({
    id: '/reports/por-metodo-pago',
    path: '/reports/por-metodo-pago',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsPorAgenciaRoute =
  AuthenticatedReportsPorAgenciaRouteImport.update({
    id: '/reports/por-agencia',
    path: '/reports/por-agencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsMovimientosRoute =
  AuthenticatedReportsMovimientosRouteImport.update({
    id: '/reports/movimientos',
    path: '/reports/movimientos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsEstadoVentasRoute =
  AuthenticatedReportsEstadoVentasRouteImport.update({
    id: '/reports/estado-ventas',
    path: '/reports/estado-ventas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsConciliacionBancardRoute =
  AuthenticatedReportsConciliacionBancardRouteImport.update({
    id: '/reports/conciliacion-bancard',
    path: '/reports/conciliacion-bancard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsComparativoRoute =
  AuthenticatedReportsComparativoRouteImport.update({
    id: '/reports/comparativo',
    path: '/reports/comparativo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsAnomaliasRoute =
  AuthenticatedReportsAnomaliasRouteImport.update({
    id: '/reports/anomalias',
    path: '/reports/anomalias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDestinationsNuevoRoute =
  AuthenticatedDestinationsNuevoRouteImport.update({
    id: '/destinations/nuevo',
    path: '/destinations/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsNuevoRoute =
  AuthenticatedClientsNuevoRouteImport.update({
    id: '/clients/nuevo',
    path: '/clients/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenciasNuevaRoute =
  AuthenticatedAgenciasNuevaRouteImport.update({
    id: '/agencias/nueva',
    path: '/agencias/nueva',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsExternalDataIndexRoute =
  AuthenticatedSettingsExternalDataIndexRouteImport.update({
    id: '/external-data/',
    path: '/external-data/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedDestinationsIdIndexRoute =
  AuthenticatedDestinationsIdIndexRouteImport.update({
    id: '/destinations/$id/',
    path: '/destinations/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsEmailIndexRoute =
  AuthenticatedClientsEmailIndexRouteImport.update({
    id: '/clients/$email/',
    path: '/clients/$email/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenciasIdIndexRoute =
  AuthenticatedAgenciasIdIndexRouteImport.update({
    id: '/agencias/$id/',
    path: '/agencias/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIdEditarRoute =
  AuthenticatedUsersIdEditarRouteImport.update({
    id: '/users/$id/editar',
    path: '/users/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsServiceChargesNuevoRoute =
  AuthenticatedSettingsServiceChargesNuevoRouteImport.update({
    id: '/settings_/service-charges_/nuevo',
    path: '/settings/service-charges/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsExternalDataDayConfigurationRoute =
  AuthenticatedSettingsExternalDataDayConfigurationRouteImport.update({
    id: '/external-data/day-configuration',
    path: '/external-data/day-configuration',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedDestinationsIdEditarRoute =
  AuthenticatedDestinationsIdEditarRouteImport.update({
    id: '/destinations/$id/editar',
    path: '/destinations/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenciasIdEditarRoute =
  AuthenticatedAgenciasIdEditarRouteImport.update({
    id: '/agencias/$id/editar',
    path: '/agencias/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsServiceChargesIdEditarRoute =
  AuthenticatedSettingsServiceChargesIdEditarRouteImport.update({
    id: '/settings_/service-charges_/$id/editar',
    path: '/settings/service-charges/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/agencias/nueva': typeof AuthenticatedAgenciasNuevaRoute
  '/clients/nuevo': typeof AuthenticatedClientsNuevoRoute
  '/destinations/nuevo': typeof AuthenticatedDestinationsNuevoRoute
  '/reports/anomalias': typeof AuthenticatedReportsAnomaliasRoute
  '/reports/comparativo': typeof AuthenticatedReportsComparativoRoute
  '/reports/conciliacion-bancard': typeof AuthenticatedReportsConciliacionBancardRoute
  '/reports/estado-ventas': typeof AuthenticatedReportsEstadoVentasRoute
  '/reports/movimientos': typeof AuthenticatedReportsMovimientosRoute
  '/reports/por-agencia': typeof AuthenticatedReportsPorAgenciaRoute
  '/reports/por-metodo-pago': typeof AuthenticatedReportsPorMetodoPagoRoute
  '/reports/por-ruta': typeof AuthenticatedReportsPorRutaRoute
  '/reports/por-servicio': typeof AuthenticatedReportsPorServicioRoute
  '/reports/por-vendedor': typeof AuthenticatedReportsPorVendedorRoute
  '/reports/resumen-financiero': typeof AuthenticatedReportsResumenFinancieroRoute
  '/reports/serie-temporal': typeof AuthenticatedReportsSerieTemporalRoute
  '/reports/ventas-sin-boleto': typeof AuthenticatedReportsVentasSinBoletoRoute
  '/sales/checkout': typeof AuthenticatedSalesCheckoutRoute
  '/sales/payment': typeof AuthenticatedSalesPaymentRoute
  '/sales/seats': typeof AuthenticatedSalesSeatsRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/service-charges': typeof AuthenticatedSettingsServiceChargesRoute
  '/users/nuevo': typeof AuthenticatedUsersNuevoRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/agencias': typeof AuthenticatedAgenciasIndexRoute
  '/caja': typeof AuthenticatedCajaIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/destinations': typeof AuthenticatedDestinationsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/agencias/$id/editar': typeof AuthenticatedAgenciasIdEditarRoute
  '/destinations/$id/editar': typeof AuthenticatedDestinationsIdEditarRoute
  '/settings/external-data/day-configuration': typeof AuthenticatedSettingsExternalDataDayConfigurationRoute
  '/settings/service-charges/nuevo': typeof AuthenticatedSettingsServiceChargesNuevoRoute
  '/users/$id/editar': typeof AuthenticatedUsersIdEditarRoute
  '/agencias/$id': typeof AuthenticatedAgenciasIdIndexRoute
  '/clients/$email': typeof AuthenticatedClientsEmailIndexRoute
  '/destinations/$id': typeof AuthenticatedDestinationsIdIndexRoute
  '/settings/external-data': typeof AuthenticatedSettingsExternalDataIndexRoute
  '/settings/service-charges/$id/editar': typeof AuthenticatedSettingsServiceChargesIdEditarRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/agencias/nueva': typeof AuthenticatedAgenciasNuevaRoute
  '/clients/nuevo': typeof AuthenticatedClientsNuevoRoute
  '/destinations/nuevo': typeof AuthenticatedDestinationsNuevoRoute
  '/reports/anomalias': typeof AuthenticatedReportsAnomaliasRoute
  '/reports/comparativo': typeof AuthenticatedReportsComparativoRoute
  '/reports/conciliacion-bancard': typeof AuthenticatedReportsConciliacionBancardRoute
  '/reports/estado-ventas': typeof AuthenticatedReportsEstadoVentasRoute
  '/reports/movimientos': typeof AuthenticatedReportsMovimientosRoute
  '/reports/por-agencia': typeof AuthenticatedReportsPorAgenciaRoute
  '/reports/por-metodo-pago': typeof AuthenticatedReportsPorMetodoPagoRoute
  '/reports/por-ruta': typeof AuthenticatedReportsPorRutaRoute
  '/reports/por-servicio': typeof AuthenticatedReportsPorServicioRoute
  '/reports/por-vendedor': typeof AuthenticatedReportsPorVendedorRoute
  '/reports/resumen-financiero': typeof AuthenticatedReportsResumenFinancieroRoute
  '/reports/serie-temporal': typeof AuthenticatedReportsSerieTemporalRoute
  '/reports/ventas-sin-boleto': typeof AuthenticatedReportsVentasSinBoletoRoute
  '/sales/checkout': typeof AuthenticatedSalesCheckoutRoute
  '/sales/payment': typeof AuthenticatedSalesPaymentRoute
  '/sales/seats': typeof AuthenticatedSalesSeatsRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/service-charges': typeof AuthenticatedSettingsServiceChargesRoute
  '/users/nuevo': typeof AuthenticatedUsersNuevoRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/agencias': typeof AuthenticatedAgenciasIndexRoute
  '/caja': typeof AuthenticatedCajaIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/destinations': typeof AuthenticatedDestinationsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/agencias/$id/editar': typeof AuthenticatedAgenciasIdEditarRoute
  '/destinations/$id/editar': typeof AuthenticatedDestinationsIdEditarRoute
  '/settings/external-data/day-configuration': typeof AuthenticatedSettingsExternalDataDayConfigurationRoute
  '/settings/service-charges/nuevo': typeof AuthenticatedSettingsServiceChargesNuevoRoute
  '/users/$id/editar': typeof AuthenticatedUsersIdEditarRoute
  '/agencias/$id': typeof AuthenticatedAgenciasIdIndexRoute
  '/clients/$email': typeof AuthenticatedClientsEmailIndexRoute
  '/destinations/$id': typeof AuthenticatedDestinationsIdIndexRoute
  '/settings/external-data': typeof AuthenticatedSettingsExternalDataIndexRoute
  '/settings/service-charges/$id/editar': typeof AuthenticatedSettingsServiceChargesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/agencias/nueva': typeof AuthenticatedAgenciasNuevaRoute
  '/_authenticated/clients/nuevo': typeof AuthenticatedClientsNuevoRoute
  '/_authenticated/destinations/nuevo': typeof AuthenticatedDestinationsNuevoRoute
  '/_authenticated/reports/anomalias': typeof AuthenticatedReportsAnomaliasRoute
  '/_authenticated/reports/comparativo': typeof AuthenticatedReportsComparativoRoute
  '/_authenticated/reports/conciliacion-bancard': typeof AuthenticatedReportsConciliacionBancardRoute
  '/_authenticated/reports/estado-ventas': typeof AuthenticatedReportsEstadoVentasRoute
  '/_authenticated/reports/movimientos': typeof AuthenticatedReportsMovimientosRoute
  '/_authenticated/reports/por-agencia': typeof AuthenticatedReportsPorAgenciaRoute
  '/_authenticated/reports/por-metodo-pago': typeof AuthenticatedReportsPorMetodoPagoRoute
  '/_authenticated/reports/por-ruta': typeof AuthenticatedReportsPorRutaRoute
  '/_authenticated/reports/por-servicio': typeof AuthenticatedReportsPorServicioRoute
  '/_authenticated/reports/por-vendedor': typeof AuthenticatedReportsPorVendedorRoute
  '/_authenticated/reports/resumen-financiero': typeof AuthenticatedReportsResumenFinancieroRoute
  '/_authenticated/reports/serie-temporal': typeof AuthenticatedReportsSerieTemporalRoute
  '/_authenticated/reports/ventas-sin-boleto': typeof AuthenticatedReportsVentasSinBoletoRoute
  '/_authenticated/sales/checkout': typeof AuthenticatedSalesCheckoutRoute
  '/_authenticated/sales/payment': typeof AuthenticatedSalesPaymentRoute
  '/_authenticated/sales/seats': typeof AuthenticatedSalesSeatsRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings_/service-charges': typeof AuthenticatedSettingsServiceChargesRoute
  '/_authenticated/users/nuevo': typeof AuthenticatedUsersNuevoRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/_authenticated/agencias/': typeof AuthenticatedAgenciasIndexRoute
  '/_authenticated/caja/': typeof AuthenticatedCajaIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/destinations/': typeof AuthenticatedDestinationsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/agencias/$id/editar': typeof AuthenticatedAgenciasIdEditarRoute
  '/_authenticated/destinations/$id/editar': typeof AuthenticatedDestinationsIdEditarRoute
  '/_authenticated/settings/external-data/day-configuration': typeof AuthenticatedSettingsExternalDataDayConfigurationRoute
  '/_authenticated/settings_/service-charges_/nuevo': typeof AuthenticatedSettingsServiceChargesNuevoRoute
  '/_authenticated/users/$id/editar': typeof AuthenticatedUsersIdEditarRoute
  '/_authenticated/agencias/$id/': typeof AuthenticatedAgenciasIdIndexRoute
  '/_authenticated/clients/$email/': typeof AuthenticatedClientsEmailIndexRoute
  '/_authenticated/destinations/$id/': typeof AuthenticatedDestinationsIdIndexRoute
  '/_authenticated/settings/external-data/': typeof AuthenticatedSettingsExternalDataIndexRoute
  '/_authenticated/settings_/service-charges_/$id/editar': typeof AuthenticatedSettingsServiceChargesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/auth/reset-password'
    | '/'
    | '/agencias/nueva'
    | '/clients/nuevo'
    | '/destinations/nuevo'
    | '/reports/anomalias'
    | '/reports/comparativo'
    | '/reports/conciliacion-bancard'
    | '/reports/estado-ventas'
    | '/reports/movimientos'
    | '/reports/por-agencia'
    | '/reports/por-metodo-pago'
    | '/reports/por-ruta'
    | '/reports/por-servicio'
    | '/reports/por-vendedor'
    | '/reports/resumen-financiero'
    | '/reports/serie-temporal'
    | '/reports/ventas-sin-boleto'
    | '/sales/checkout'
    | '/sales/payment'
    | '/sales/seats'
    | '/settings/appearance'
    | '/settings/service-charges'
    | '/users/nuevo'
    | '/api/auth/verify-email'
    | '/agencias'
    | '/caja'
    | '/clients'
    | '/destinations'
    | '/reports'
    | '/sales'
    | '/settings/'
    | '/users'
    | '/agencias/$id/editar'
    | '/destinations/$id/editar'
    | '/settings/external-data/day-configuration'
    | '/settings/service-charges/nuevo'
    | '/users/$id/editar'
    | '/agencias/$id'
    | '/clients/$email'
    | '/destinations/$id'
    | '/settings/external-data'
    | '/settings/service-charges/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/auth/reset-password'
    | '/'
    | '/agencias/nueva'
    | '/clients/nuevo'
    | '/destinations/nuevo'
    | '/reports/anomalias'
    | '/reports/comparativo'
    | '/reports/conciliacion-bancard'
    | '/reports/estado-ventas'
    | '/reports/movimientos'
    | '/reports/por-agencia'
    | '/reports/por-metodo-pago'
    | '/reports/por-ruta'
    | '/reports/por-servicio'
    | '/reports/por-vendedor'
    | '/reports/resumen-financiero'
    | '/reports/serie-temporal'
    | '/reports/ventas-sin-boleto'
    | '/sales/checkout'
    | '/sales/payment'
    | '/sales/seats'
    | '/settings/appearance'
    | '/settings/service-charges'
    | '/users/nuevo'
    | '/api/auth/verify-email'
    | '/agencias'
    | '/caja'
    | '/clients'
    | '/destinations'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/users'
    | '/agencias/$id/editar'
    | '/destinations/$id/editar'
    | '/settings/external-data/day-configuration'
    | '/settings/service-charges/nuevo'
    | '/users/$id/editar'
    | '/agencias/$id'
    | '/clients/$email'
    | '/destinations/$id'
    | '/settings/external-data'
    | '/settings/service-charges/$id/editar'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/auth/reset-password'
    | '/_authenticated/'
    | '/_authenticated/agencias/nueva'
    | '/_authenticated/clients/nuevo'
    | '/_authenticated/destinations/nuevo'
    | '/_authenticated/reports/anomalias'
    | '/_authenticated/reports/comparativo'
    | '/_authenticated/reports/conciliacion-bancard'
    | '/_authenticated/reports/estado-ventas'
    | '/_authenticated/reports/movimientos'
    | '/_authenticated/reports/por-agencia'
    | '/_authenticated/reports/por-metodo-pago'
    | '/_authenticated/reports/por-ruta'
    | '/_authenticated/reports/por-servicio'
    | '/_authenticated/reports/por-vendedor'
    | '/_authenticated/reports/resumen-financiero'
    | '/_authenticated/reports/serie-temporal'
    | '/_authenticated/reports/ventas-sin-boleto'
    | '/_authenticated/sales/checkout'
    | '/_authenticated/sales/payment'
    | '/_authenticated/sales/seats'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings_/service-charges'
    | '/_authenticated/users/nuevo'
    | '/api/auth/verify-email'
    | '/_authenticated/agencias/'
    | '/_authenticated/caja/'
    | '/_authenticated/clients/'
    | '/_authenticated/destinations/'
    | '/_authenticated/reports/'
    | '/_authenticated/sales/'
    | '/_authenticated/settings/'
    | '/_authenticated/users/'
    | '/_authenticated/agencias/$id/editar'
    | '/_authenticated/destinations/$id/editar'
    | '/_authenticated/settings/external-data/day-configuration'
    | '/_authenticated/settings_/service-charges_/nuevo'
    | '/_authenticated/users/$id/editar'
    | '/_authenticated/agencias/$id/'
    | '/_authenticated/clients/$email/'
    | '/_authenticated/destinations/$id/'
    | '/_authenticated/settings/external-data/'
    | '/_authenticated/settings_/service-charges_/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  ApiAuthVerifyEmailRoute: typeof ApiAuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/destinations/': {
      id: '/_authenticated/destinations/'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof AuthenticatedDestinationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caja/': {
      id: '/_authenticated/caja/'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof AuthenticatedCajaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agencias/': {
      id: '/_authenticated/agencias/'
      path: '/agencias'
      fullPath: '/agencias'
      preLoaderRoute: typeof AuthenticatedAgenciasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/verify-email': {
      id: '/api/auth/verify-email'
      path: '/api/auth/verify-email'
      fullPath: '/api/auth/verify-email'
      preLoaderRoute: typeof ApiAuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/nuevo': {
      id: '/_authenticated/users/nuevo'
      path: '/users/nuevo'
      fullPath: '/users/nuevo'
      preLoaderRoute: typeof AuthenticatedUsersNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings_/service-charges': {
      id: '/_authenticated/settings_/service-charges'
      path: '/settings/service-charges'
      fullPath: '/settings/service-charges'
      preLoaderRoute: typeof AuthenticatedSettingsServiceChargesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/sales/seats': {
      id: '/_authenticated/sales/seats'
      path: '/sales/seats'
      fullPath: '/sales/seats'
      preLoaderRoute: typeof AuthenticatedSalesSeatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/payment': {
      id: '/_authenticated/sales/payment'
      path: '/sales/payment'
      fullPath: '/sales/payment'
      preLoaderRoute: typeof AuthenticatedSalesPaymentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/checkout': {
      id: '/_authenticated/sales/checkout'
      path: '/sales/checkout'
      fullPath: '/sales/checkout'
      preLoaderRoute: typeof AuthenticatedSalesCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/ventas-sin-boleto': {
      id: '/_authenticated/reports/ventas-sin-boleto'
      path: '/reports/ventas-sin-boleto'
      fullPath: '/reports/ventas-sin-boleto'
      preLoaderRoute: typeof AuthenticatedReportsVentasSinBoletoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/serie-temporal': {
      id: '/_authenticated/reports/serie-temporal'
      path: '/reports/serie-temporal'
      fullPath: '/reports/serie-temporal'
      preLoaderRoute: typeof AuthenticatedReportsSerieTemporalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/resumen-financiero': {
      id: '/_authenticated/reports/resumen-financiero'
      path: '/reports/resumen-financiero'
      fullPath: '/reports/resumen-financiero'
      preLoaderRoute: typeof AuthenticatedReportsResumenFinancieroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/por-vendedor': {
      id: '/_authenticated/reports/por-vendedor'
      path: '/reports/por-vendedor'
      fullPath: '/reports/por-vendedor'
      preLoaderRoute: typeof AuthenticatedReportsPorVendedorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/por-servicio': {
      id: '/_authenticated/reports/por-servicio'
      path: '/reports/por-servicio'
      fullPath: '/reports/por-servicio'
      preLoaderRoute: typeof AuthenticatedReportsPorServicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/por-ruta': {
      id: '/_authenticated/reports/por-ruta'
      path: '/reports/por-ruta'
      fullPath: '/reports/por-ruta'
      preLoaderRoute: typeof AuthenticatedReportsPorRutaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/por-metodo-pago': {
      id: '/_authenticated/reports/por-metodo-pago'
      path: '/reports/por-metodo-pago'
      fullPath: '/reports/por-metodo-pago'
      preLoaderRoute: typeof AuthenticatedReportsPorMetodoPagoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/por-agencia': {
      id: '/_authenticated/reports/por-agencia'
      path: '/reports/por-agencia'
      fullPath: '/reports/por-agencia'
      preLoaderRoute: typeof AuthenticatedReportsPorAgenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/movimientos': {
      id: '/_authenticated/reports/movimientos'
      path: '/reports/movimientos'
      fullPath: '/reports/movimientos'
      preLoaderRoute: typeof AuthenticatedReportsMovimientosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/estado-ventas': {
      id: '/_authenticated/reports/estado-ventas'
      path: '/reports/estado-ventas'
      fullPath: '/reports/estado-ventas'
      preLoaderRoute: typeof AuthenticatedReportsEstadoVentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/conciliacion-bancard': {
      id: '/_authenticated/reports/conciliacion-bancard'
      path: '/reports/conciliacion-bancard'
      fullPath: '/reports/conciliacion-bancard'
      preLoaderRoute: typeof AuthenticatedReportsConciliacionBancardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/comparativo': {
      id: '/_authenticated/reports/comparativo'
      path: '/reports/comparativo'
      fullPath: '/reports/comparativo'
      preLoaderRoute: typeof AuthenticatedReportsComparativoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/anomalias': {
      id: '/_authenticated/reports/anomalias'
      path: '/reports/anomalias'
      fullPath: '/reports/anomalias'
      preLoaderRoute: typeof AuthenticatedReportsAnomaliasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/destinations/nuevo': {
      id: '/_authenticated/destinations/nuevo'
      path: '/destinations/nuevo'
      fullPath: '/destinations/nuevo'
      preLoaderRoute: typeof AuthenticatedDestinationsNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/nuevo': {
      id: '/_authenticated/clients/nuevo'
      path: '/clients/nuevo'
      fullPath: '/clients/nuevo'
      preLoaderRoute: typeof AuthenticatedClientsNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agencias/nueva': {
      id: '/_authenticated/agencias/nueva'
      path: '/agencias/nueva'
      fullPath: '/agencias/nueva'
      preLoaderRoute: typeof AuthenticatedAgenciasNuevaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/external-data/': {
      id: '/_authenticated/settings/external-data/'
      path: '/external-data'
      fullPath: '/settings/external-data'
      preLoaderRoute: typeof AuthenticatedSettingsExternalDataIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/destinations/$id/': {
      id: '/_authenticated/destinations/$id/'
      path: '/destinations/$id'
      fullPath: '/destinations/$id'
      preLoaderRoute: typeof AuthenticatedDestinationsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$email/': {
      id: '/_authenticated/clients/$email/'
      path: '/clients/$email'
      fullPath: '/clients/$email'
      preLoaderRoute: typeof AuthenticatedClientsEmailIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agencias/$id/': {
      id: '/_authenticated/agencias/$id/'
      path: '/agencias/$id'
      fullPath: '/agencias/$id'
      preLoaderRoute: typeof AuthenticatedAgenciasIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$id/editar': {
      id: '/_authenticated/users/$id/editar'
      path: '/users/$id/editar'
      fullPath: '/users/$id/editar'
      preLoaderRoute: typeof AuthenticatedUsersIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings_/service-charges_/nuevo': {
      id: '/_authenticated/settings_/service-charges_/nuevo'
      path: '/settings/service-charges/nuevo'
      fullPath: '/settings/service-charges/nuevo'
      preLoaderRoute: typeof AuthenticatedSettingsServiceChargesNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/external-data/day-configuration': {
      id: '/_authenticated/settings/external-data/day-configuration'
      path: '/external-data/day-configuration'
      fullPath: '/settings/external-data/day-configuration'
      preLoaderRoute: typeof AuthenticatedSettingsExternalDataDayConfigurationRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/destinations/$id/editar': {
      id: '/_authenticated/destinations/$id/editar'
      path: '/destinations/$id/editar'
      fullPath: '/destinations/$id/editar'
      preLoaderRoute: typeof AuthenticatedDestinationsIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agencias/$id/editar': {
      id: '/_authenticated/agencias/$id/editar'
      path: '/agencias/$id/editar'
      fullPath: '/agencias/$id/editar'
      preLoaderRoute: typeof AuthenticatedAgenciasIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings_/service-charges_/$id/editar': {
      id: '/_authenticated/settings_/service-charges_/$id/editar'
      path: '/settings/service-charges/$id/editar'
      fullPath: '/settings/service-charges/$id/editar'
      preLoaderRoute: typeof AuthenticatedSettingsServiceChargesIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsExternalDataDayConfigurationRoute: typeof AuthenticatedSettingsExternalDataDayConfigurationRoute
  AuthenticatedSettingsExternalDataIndexRoute: typeof AuthenticatedSettingsExternalDataIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
    AuthenticatedSettingsExternalDataDayConfigurationRoute:
      AuthenticatedSettingsExternalDataDayConfigurationRoute,
    AuthenticatedSettingsExternalDataIndexRoute:
      AuthenticatedSettingsExternalDataIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAgenciasNuevaRoute: typeof AuthenticatedAgenciasNuevaRoute
  AuthenticatedClientsNuevoRoute: typeof AuthenticatedClientsNuevoRoute
  AuthenticatedDestinationsNuevoRoute: typeof AuthenticatedDestinationsNuevoRoute
  AuthenticatedReportsAnomaliasRoute: typeof AuthenticatedReportsAnomaliasRoute
  AuthenticatedReportsComparativoRoute: typeof AuthenticatedReportsComparativoRoute
  AuthenticatedReportsConciliacionBancardRoute: typeof AuthenticatedReportsConciliacionBancardRoute
  AuthenticatedReportsEstadoVentasRoute: typeof AuthenticatedReportsEstadoVentasRoute
  AuthenticatedReportsMovimientosRoute: typeof AuthenticatedReportsMovimientosRoute
  AuthenticatedReportsPorAgenciaRoute: typeof AuthenticatedReportsPorAgenciaRoute
  AuthenticatedReportsPorMetodoPagoRoute: typeof AuthenticatedReportsPorMetodoPagoRoute
  AuthenticatedReportsPorRutaRoute: typeof AuthenticatedReportsPorRutaRoute
  AuthenticatedReportsPorServicioRoute: typeof AuthenticatedReportsPorServicioRoute
  AuthenticatedReportsPorVendedorRoute: typeof AuthenticatedReportsPorVendedorRoute
  AuthenticatedReportsResumenFinancieroRoute: typeof AuthenticatedReportsResumenFinancieroRoute
  AuthenticatedReportsSerieTemporalRoute: typeof AuthenticatedReportsSerieTemporalRoute
  AuthenticatedReportsVentasSinBoletoRoute: typeof AuthenticatedReportsVentasSinBoletoRoute
  AuthenticatedSalesCheckoutRoute: typeof AuthenticatedSalesCheckoutRoute
  AuthenticatedSalesPaymentRoute: typeof AuthenticatedSalesPaymentRoute
  AuthenticatedSalesSeatsRoute: typeof AuthenticatedSalesSeatsRoute
  AuthenticatedSettingsServiceChargesRoute: typeof AuthenticatedSettingsServiceChargesRoute
  AuthenticatedUsersNuevoRoute: typeof AuthenticatedUsersNuevoRoute
  AuthenticatedAgenciasIndexRoute: typeof AuthenticatedAgenciasIndexRoute
  AuthenticatedCajaIndexRoute: typeof AuthenticatedCajaIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedDestinationsIndexRoute: typeof AuthenticatedDestinationsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedAgenciasIdEditarRoute: typeof AuthenticatedAgenciasIdEditarRoute
  AuthenticatedDestinationsIdEditarRoute: typeof AuthenticatedDestinationsIdEditarRoute
  AuthenticatedSettingsServiceChargesNuevoRoute: typeof AuthenticatedSettingsServiceChargesNuevoRoute
  AuthenticatedUsersIdEditarRoute: typeof AuthenticatedUsersIdEditarRoute
  AuthenticatedAgenciasIdIndexRoute: typeof AuthenticatedAgenciasIdIndexRoute
  AuthenticatedClientsEmailIndexRoute: typeof AuthenticatedClientsEmailIndexRoute
  AuthenticatedDestinationsIdIndexRoute: typeof AuthenticatedDestinationsIdIndexRoute
  AuthenticatedSettingsServiceChargesIdEditarRoute: typeof AuthenticatedSettingsServiceChargesIdEditarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAgenciasNuevaRoute: AuthenticatedAgenciasNuevaRoute,
  AuthenticatedClientsNuevoRoute: AuthenticatedClientsNuevoRoute,
  AuthenticatedDestinationsNuevoRoute: AuthenticatedDestinationsNuevoRoute,
  AuthenticatedReportsAnomaliasRoute: AuthenticatedReportsAnomaliasRoute,
  AuthenticatedReportsComparativoRoute: AuthenticatedReportsComparativoRoute,
  AuthenticatedReportsConciliacionBancardRoute:
    AuthenticatedReportsConciliacionBancardRoute,
  AuthenticatedReportsEstadoVentasRoute: AuthenticatedReportsEstadoVentasRoute,
  AuthenticatedReportsMovimientosRoute: AuthenticatedReportsMovimientosRoute,
  AuthenticatedReportsPorAgenciaRoute: AuthenticatedReportsPorAgenciaRoute,
  AuthenticatedReportsPorMetodoPagoRoute:
    AuthenticatedReportsPorMetodoPagoRoute,
  AuthenticatedReportsPorRutaRoute: AuthenticatedReportsPorRutaRoute,
  AuthenticatedReportsPorServicioRoute: AuthenticatedReportsPorServicioRoute,
  AuthenticatedReportsPorVendedorRoute: AuthenticatedReportsPorVendedorRoute,
  AuthenticatedReportsResumenFinancieroRoute:
    AuthenticatedReportsResumenFinancieroRoute,
  AuthenticatedReportsSerieTemporalRoute:
    AuthenticatedReportsSerieTemporalRoute,
  AuthenticatedReportsVentasSinBoletoRoute:
    AuthenticatedReportsVentasSinBoletoRoute,
  AuthenticatedSalesCheckoutRoute: AuthenticatedSalesCheckoutRoute,
  AuthenticatedSalesPaymentRoute: AuthenticatedSalesPaymentRoute,
  AuthenticatedSalesSeatsRoute: AuthenticatedSalesSeatsRoute,
  AuthenticatedSettingsServiceChargesRoute:
    AuthenticatedSettingsServiceChargesRoute,
  AuthenticatedUsersNuevoRoute: AuthenticatedUsersNuevoRoute,
  AuthenticatedAgenciasIndexRoute: AuthenticatedAgenciasIndexRoute,
  AuthenticatedCajaIndexRoute: AuthenticatedCajaIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedDestinationsIndexRoute: AuthenticatedDestinationsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedAgenciasIdEditarRoute: AuthenticatedAgenciasIdEditarRoute,
  AuthenticatedDestinationsIdEditarRoute:
    AuthenticatedDestinationsIdEditarRoute,
  AuthenticatedSettingsServiceChargesNuevoRoute:
    AuthenticatedSettingsServiceChargesNuevoRoute,
  AuthenticatedUsersIdEditarRoute: AuthenticatedUsersIdEditarRoute,
  AuthenticatedAgenciasIdIndexRoute: AuthenticatedAgenciasIdIndexRoute,
  AuthenticatedClientsEmailIndexRoute: AuthenticatedClientsEmailIndexRoute,
  AuthenticatedDestinationsIdIndexRoute: AuthenticatedDestinationsIdIndexRoute,
  AuthenticatedSettingsServiceChargesIdEditarRoute:
    AuthenticatedSettingsServiceChargesIdEditarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  ApiAuthVerifyEmailRoute: ApiAuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
