name: Deploy Stage

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/proyectos/psaonlie_suite
            git fetch origin
            git checkout ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}
            
            docker compose down
            docker compose up -d --build
            
            echo "Deploy completado desde rama: ${{ github.ref_name }}"

